### ISSUE TITLE
Update pydoctor version and remove Twisted pydoctor custom code that is now available as standard features. 

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#10066]
|[<img alt="adiroiban's avatar" src="https://avatars.githubusercontent.com/u/204609?s=50" width="50" height="50">](https://github.com/adiroiban)| @adiroiban reported|
|-|-|
|Trac ID|trac#10066|
|Type|enhancement|
|Created|2020-12-10 19:24:32Z|

By for Sphinx, make sure we don't exit on first warning... so that we can see all errors in single go.
Put the warnings in a file, and fail if file is not empty.

For pydoctor, use the latest command line argument and don't use our custom script.

<details><summary>Searchable metadata</summary>

```
trac-id__10066 10066
type__enhancement enhancement
reporter__adiroiban adiroiban
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__new new
resolution__None None
component__core core
keywords__None None
time__1607628272163444 1607628272163444
changetime__1607628272163444 1607628272163444
version__None None
owner__None None

```
</details>

**Comment by tristanlatr** [comment]
Pydoctor generated more warning than before, maybe it won’t be possible to have a 100% clean build.

**Comment by adiroiban** [comment]
I am now setting up the branch on my local system.

I will give it a try and push the changes.

It looks like with `tox -e narrativedocs` the API docs are generated, but it won't fail on errors.

**Comment by adiroiban** [comment]
@tristanlatr see the changes for https://github.com/twisted/twisted/pull/11578

I got errors like

```
/home/adi/chevah/twisted/.tox/apidocs/lib/python3.10/site-packages/pydoctor/templatewriter/__init__.py:295: UserWarning: Your custom template 'footer.html' is out of date, information might be missing. Latest templates are available to download from our github.
```

for the targeted PR, my goal is to see the CI red on pydoctor build failures.

The pydoctor update and pydoctor build script are secondary

So maybe we should look for a separate PR to to upgrade pydoctor, cleanup the templates and other scripts.

**Comment by tristanlatr** [comment]
This warning is serious, since the `footer.html` is used to import scripts, it must be updated from https://github.com/twisted/pydoctor/blob/22.5.x/pydoctor/themes/base/footer.html while updating to pydoctor 22.5

**Comment by adiroiban** [comment]
Thanks. I think that I will leave the pydoctor upgrade for another PR, and for this ticket, just focus on fixing the current pydoctor warnings.

**Comment by adiroiban** [comment]
@tristanlatr at the same time, my question.

Do we really need a custom template for Twisted?

At this point, I think that is better to just use the pydoctor default template.

If there is anything that is needed by Twisted, it should be needed by other project and thus included in the main template.

----------

I see the folowing customizations in Twisted

* header - go to latest version of API - I think this is useful for any other project
* footer -google analytics - we should not need this. Google tracking is bad :) ... but maybe add support for open source trackers like Plausible
* common - I don't know what is specific to twisted

**Comment by tristanlatr** [comment]
> Do we really need a custom template for Twisted?

Yes, most probably. I'll try to explain why while answering the specific aspects.

> header - go to latest version of API - I think this is useful for any other project

Yes it could be useful for other project but I feel like it might be hard to generalize since the setup can vary a lot.
Maybe a discussion with the maintainers of python-igraph could be started, they host api docs for several versions and they allow to switch from one to another. But their setup is much more complex than twisted's.

> footer -google analytics - we should not need this. Google tracking is bad :) ... but maybe add support for open source trackers like Plausible

In any case, I'm against adding analytics platform integration as a builtin option of pydoctor, so using a template is the way to go if you want analytics data. Again, this kind of setup varies a lot projects to projects.

> common - I don't know what is specific to twisted

The customization of this template is needed by the deprecation notice logic, which is now supported in the latest (master) version of pydoctor. But I do not recommend using the master version at this time since it contains bugs right now. So it must be kept if you are upgrading to pydoctor 22.5.x.

Hope this answers your question,

I'll try to merge the pending PRs and publish a new version of pydoctor before september, but I cant't really commit to that deadline. 

Talk to you later,
