### ISSUE TITLE
tls "Internal Error" When trying to serve clients using tls1.0

### ISSUE THREAD

**Issue by Hay1tsme** [twisted/twisted#11568]
I am building a server that interacts with legacy applications that only use tls1.0. When these services attempt to connect, the connection fails. Wireshark ravels that this is because the server sends a fatal "Internal Error" in response to the client hello. TLS 1.2 works as expected, only TLS 1.0 appears to have this problem. I am using twisted v22.4.0

Code:
```
endpoints.serverFromString(reactor, f"ssl:8443:interface=0.0.0.0:privateKey=server.key:certKey=server.pem").listen(server.Site(SecSite()))

reactor.run()
```

Adding sslmethod=TLSv1_METHOD forces ALL connections to use tlsv1, and all fail in the same way.

**Comment by adiroiban** [comment]
Hi,

Thanks for the report.

Can you add a minimal example in which `sslmethod=TLSv1_METHOD` is used, int the format suggested here http://sscce.org/ ?

What OpenSSL library do you use and which version of pyOpenSSL and cryptography library? Does it support TLSv1 ?

You can try `sslmethod=TLS_method`

Cheers

**Comment by Hay1tsme** [comment]
sslmethod=TLS_method results in "AttributeError: module 'OpenSSL.SSL' has no attribute 'TLS_method'"

OpenSSL 1.1.1n, cryptography 37.0.2, pyOpenSSL 22.0.0, They all seem to support tlsv1

```
from twisted.web import server
from twisted.internet import reactor, endpoints

endpoints.serverFromString(reactor, f"ssl:8443:sslmethod=TLSv1_METHOD:interface=0.0.0.0:privateKey=server.key:certKey=server.pem").listen(server.Site(SecSite()))

reactor.run()
```
...
```
from twisted.web import resource

class SecSite(resource.Resource):
    isLeaf = True
    def render_GET(self, request):
        return b"testing!"
```

**Comment by glyph** [comment]
It is very unlikely that your OpenSSL 1.1.1n supports TLSv1.0 unless you carefully compiled it by hand to do so; it is disabled almost everywhere by default now.  It's not really safe to use.

In general, unless you see a traceback that comes from Twisted, this is going to be an OpenSSL library configuration issue, and nothing to do with Twisted. When you use the legacy `sslmethod=` configuration parameter, we just pass it straight through to the library.

I'm going to close this issue because we don't really support TLS versions this old, and support will probably be removed from Twisted entirely at some point since it's a security risk to even allow users to turn this on.  However, as long as we support the `sslmethod=` parameter at all we should still probably fix bugs in its use, so if you can conclusively prove that it's Twisted and not OpenSSL, Cryptography or pyOpenSSL that's causing this issue, we could fix the bug.  But you will need to supply very precise OS and library versions, and ideally a self-contained Docker container with the precise versions of everything you're using so that we don't have to do diagnostics on your build environment.
