### ISSUE TITLE
Remove unnecessary permissions in workflows

### ISSUE THREAD

**Issue by sashashura** [twisted/twisted#11631]
This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or action) is restricted.
It is recommended to have [most strict permissions on the top level](https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions) and grant write permissions on [job level](https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs) case by case.

**Comment by sashashura** [comment]
https://github.com/twisted/twisted/pull/11632

**Comment by adiroiban** [comment]
Thanks for your work.

Just a note.

If `Fixes #1234` is added to the PR description,  GitHub will automatically link back that PR.

it will also insert this under the issue title: May be fixed by https://github.com/twisted/twisted/pull/11632

![image](https://user-images.githubusercontent.com/204609/188246357-e719a829-b1f1-4068-8c1d-fbbbc9f84b73.png)

The `Fixes #1234` will also make sure that the issue is auto-closed when the PR is closed.
