### ISSUE TITLE
Deprecate twisted.words

### ISSUE THREAD

**Issue by adiroiban** [twisted/twisted#11968]
twisted.words is not really maintained.

I am not sure if the jabber or IRC implementation is production-ready.

I think continuing to keep the code just adds unnecessarily extra work to maintainers ... for example when adding annotations

If that code is still useful, I think we can move it into something like twisted/txirc and twisted/txjabber 

I am +1 for the deprecation and I think I am not the  only one :)

**Comment by glyph** [comment]
I'm -0 on this, but I'd be -1 if I had the bandwidth to fully maintain it. I'm sad that we never got an IRCv3 implementation, but I guess if I wanted it bad enough I would have contributed one.

In any case something huge like this would need to be raised on the mailing list first, we cannot expect users to subscribe to every bug.  (We can't actually expect them to be on the mailing list _either_, but it is at least the thing that you're _supposed_ to do if you care about big changes to Twisted :))

**Comment by ralphm** [comment]
I can't talk for the IRC code, but the XMPP code in Twisted, while old, is still in (production) use in at least one project: https://libervia.org/. I haven't had the bandwidth to work on this recently, but am unaware of any particular issues with it. I'll reach out to @goffi-contrib and see how we best move forward.

**Comment by goffi-contrib** [comment]
Indeed, the XMPP code, which includes the `words.xish` and `words.protocols.jabber` packages, is an essential component of the project [Libervia](https://libervia.org) that I am currently maintaining. Thanks to @ralphm for bringing this to my attention. The code is stable and requires minimal maintenance. Given the nature of XMPP, any evolution primarily occurs through the implementation of XEPs, which I handle directly within my project. The Twisted foundation remains crucial to its functioning. I kindly request that you do not deprecate it.

**Comment by adiroiban** [comment]
well... AFAIK, there is no active maintainer for the XMPP code :(

For example, we have this MITM report from June 2017 #9206 which wasn't addressed by any other  contributor

There might be people using twisted.words but without a maintainer, it can be a security issue.

I agree that this should also be raised over the mailing list

**Comment by glyph** [comment]
@ralphm @goffi-contrib Thanks for chiming in!

Given that XEPs are where the action is, do you have any thoughts on how to build enthusiasm for future XMPP-specific maintenance?  I don't want anyone here to feel like they personally need to have the bandwidth and energy for taking over maintenance, but attracting someone interested in the space to help out with this would really ease the burden here.

**Comment by goffi-contrib** [comment]
@adiroiban I was not aware of this issue, and I have not yet utilized the server code. However, it appears to be an easily fixable problem—namely, by making TLS mandatory.

@glyph While I'd be happy to contribute, my current workload is quite substantial, particularly at the moment. I might be able to delve into it more deeply in a few months. As I mentioned earlier, I don't believe there's a significant amount of maintenance required; I've been working with it for 15 years and have found it to be stable with minimal changes needed over time.

**Comment by ralphm** [comment]
For completeness, I have closed the referenced ticket on that security issue, since that has already been addressed in 2019. I'm happy to look into any maintenance that is required to keep this in Twisted proper.

**Comment by adiroiban** [comment]
Thanks for your feedback about XMPP.
What about IRC ?
Is the IRC code usable ?

I think the IRC code was migrated to Py3 with the bare minimum, with only ASCII support #9444

**Comment by glyph** [comment]
> @glyph While I'd be happy to contribute, my current workload is quite substantial, particularly at the moment. I might be able to delve into it more deeply in a few months.

This is why I specifically said "I don't want anyone here to feel like they personally need to have the bandwidth and energy" :).  What I was asking for was ideas, based on your knowledge of the state of the XMPP community, for someone who may have interest in or bandwidth for a project like this.

> As I mentioned earlier, I don't believe there's a significant amount of maintenance required; I've been working with it for 15 years and have found it to be stable with minimal changes needed over time.

I would tend to agree, but @adiroiban seems to think there is a lot of work to be done to keep the XMPP code up to current coding standards.

**Comment by glyph** [comment]
> Is the IRC code usable ?

Here's a Twisted IRC bot with commits in July of this year:

https://github.com/JohnMaguire/Cardinal

Here's one that relies on 23.8.0

https://github.com/DesertBot/DesertBot

Here's a slightly more outdated one from 5 years ago, but that might still work as far as I know

https://github.com/AWilliams17/Servo-IRCBot

**Comment by glyph** [comment]
> I would tend to agree, but @adiroiban seems to think there is a lot of work to be done to keep the XMPP code up to current coding standards.

(and I should note, he is *doing* that work so his opinion carries somewhat more weight than my casual impression :))

**Comment by adiroiban** [comment]
Thanks for your feedbacks

It's not that hard to keep the current code and tests for twisted.words.

I was expecting that by now `[matrix]` won and IRC and XMMP are a thing of the past.

But without a maintainer, we might have code that has all the tests passing but is full of security issues, that are reported and not addressed.

I am going to close this now.

For now, we can keep `twisted.words`

I am happy to reopen this ticket at any time and reconsider :)

**Comment by goffi-contrib** [comment]
> Thanks for your feedbacks
> 
> It's not that hard to keep the current code and tests for twisted.words.

Thank you for the feedback and for your contributions to Twisted as well!

> I was expecting that by now [matrix] won and IRC and XMMP are a thing of the past.

Contrary to that belief, XMPP is still very much alive and actively used.

> But without a maintainer, we might have code that has all the tests passing but is full of security issues, that are reported and not addressed.

Please feel free to CC me on any XMPP-related security issues. I'll do my best to contribute fixes when time permits.

**Comment by adiroiban** [comment]
Thanks for the help.

My "philosopy"/wish is to only have twisted/twisted repo with the core framework and low-level protocols like TLS and move the other protocols to sub-projects like twisted/txwords

In this way, you can subscribe to the txwords repo and automatically receive only XMPP related bugs or security reports.

But, no problem. We can continue to keep the existing structure.

**Comment by glyph** [comment]
> My "philosopy"/wish is to only have twisted/twisted repo with the core framework and low-level protocols like TLS and move the other protocols to sub-projects like twisted/txwords

I specifically do not want this, for two reasons:

1. We would need to have CI on the core repo that blocks on CI for a half a dozen other repos, which would be annoying to coordinate.  If we don't do that, then all these other projects bitrot and we ship broken releases.  Having coordinated / consolidated maintenance is part of the *appeal* of Twisted and I think it would be good to have more of it, not less.  (i.e. Treq should probably be folded in to Twisted proper...)
2. We tried this before, and it was a real mess that we spent the better part of 5 years unwinding because it went so poorly.  Now, to be fair, the *way* we did it was a hodgepodge of broken tools — this predated `pip`, among other things — and we tried to do it in a weird, nonstandard way with a monorepo and a complete separation between sdist contents and repo contents.  But, with modern tools, while splitting out lots more projects is more of a repeatable process that would require far less weird & probably broken custom tooling, it *also* will add *far* more overhead than we had the last time we did this.  More GHA, PyPI, RTD, Codecov, Pre-Commit, hatchling,  configurations to manage; instead of merely haphazardly sometimes replicating changes across treq, klein, twisted, pydoctor, ldaptor, we'd expand the cartesian product to encompass numerous other projects.

To provide a visualization of the effort involved, here's a table of the projects we *already* maintain, and the tools that we *should* be maintaining the configuration for across them:

|                     | **github actions** | **pre-commit** | **isort** | **black** | **mypy** | **hatchling** | **flake8** | **fancy-pypi-readme** | **towncrier** | **codecov** | **readthedocs** |
| ------------------- | ------------------ | -------------- | --------- | --------- | -------- | ------------- | ---------- | --------------------- | ------------- | ----------- | --------------- |
| twisted             |                    |                |           |           |          |               |            |                       |               |             |                 |
| klein               |                    |                |           |           |          |               |            |                       |               |             |                 |
| ldaptor             |                    |                |           |           |          |               |            |                       |               |             |                 |
| pydoctor            |                    |                |           |           |          |               |            |                       |               |             |                 |
| ampoule             |                    |                |           |           |          |               |            |                       |               |             |                 |
| constantly          |                    |                |           |           |          |               |            |                       |               |             |                 |
| towncrier           |                    |                |           |           |          |               |            |                       |               |             |                 |
| incremental         |                    |                |           |           |          |               |            |                       |               |             |                 |
| qt5reactor          |                    |                |           |           |          |               |            |                       |               |             |                 |
| twisted-iocpsupport |                    |                |           |           |          |               |            |                       |               |             |                 |
| treq                |                    |                |           |           |          |               |            |                       |               |             |                 |

Do you want to multiply this out by 10-15 additional projects, each a fine-grained thing for a single protocol, without first developing some kind of tool to help us manage the existing burden that we're not really meeting?

If we *do* have the bandwidth for such a project, I'd suggest that the place to start is actually with Deferred and FilePath, getting the core lightweight abstractions out of Twisted because those can have a smaller test matrix and less platform-dependent behavior that needs to be tested.  The protocols all need similar levels of integration testing along with TLS, and the reactors all need OS-sensitive configuration.

**Comment by adiroiban** [comment]
Thanks for the explanation.

We can keep twisted.words as it is. No problem.

**Comment by glyph** [comment]
> Thanks for the explanation.

No worries, glad it was helpful.

> We can keep twisted.words as it is. No problem.

To be clear, I am not against the idea *in the long term*, hopefully the explanation conveyed that the main problem is the fact that it puts the cart before the horse :)
