### ISSUE TITLE
`constantly` needs some help to move to py3.12

### ISSUE THREAD

**Issue by chenrui333** [twisted/twisted#12025]
I know it might not be the right place, but `constantly` project need some help to get into py3.12 (it would affect lots of downstream usage)

relates to:
- https://github.com/twisted/constantly/issues/29

Currently, there is some PR patch for py3.12 config change, https://github.com/twisted/constantly/pull/31

**Comment by adiroiban** [comment]
Thanks for the heads up.

I think that twisted is already using constantly on py 3.12 ... and it works.

But there might be things not working.


continue the work for fixing this on https://github.com/twisted/constantly/pull/31

--------

Not sure if for Twisted we want to do the upgrade


I will leave this open for now, as maybe we might want to upgrade constantly, once the new release is done.

**Comment by glyph** [comment]
> I think that twisted is already using constantly on py 3.12 ... and it works.

I believe that the issue here has to do with the fact that Homebrew wants to do a source build, and while constantly works fine from its universal wheel, the bundled `versioneer` that runs at build time is not compatible with 3.12 and is causing build issues.

In any case this has nothing to do with twisted/twisted, so I'm closing here, but the issue should definitely be addressed.
