### ISSUE TITLE
TLS connection fails with service-identity 23.1.0

### ISSUE THREAD

**Issue by yannbouteiller** [twisted/twisted#12074]
**Describe the incorrect behavior you saw**
When using the last version of `service-identity` (`service-identity==23.1.0`), Twisted fails to establish TLS connections.
When using version `service-identity==21.1.0` instead, TLS connections are properly established.

**Describe how to cause this behavior**
On Windows:
- Install the last version of `service-identity`: `pip install service-identity==23.1.0`
- Extract this test folder (contains a python script, and a self signed TLS key/certificate pair): [twisted_test.zip](https://github.com/twisted/twisted/files/13835140/twisted_test.zip)
- run the script: `python twisted_test.py`

Here is a copy of `twisted_test.py`:
```python
import time

import os

import OpenSSL
from twisted.python.filepath import FilePath
from twisted.internet import ssl
from twisted.internet.protocol import Protocol, ReconnectingClientFactory, Factory

import logging

logging.basicConfig()
logger = logging.getLogger()
logger.setLevel(logging.DEBUG)


class ServerProtocol(Protocol):

    def __init__(self, server):
        self._server = server

    def connectionMade(self):
        logger.info("SERVER_PROTOCOL: Connection made from client")

    def connectionLost(self, reason):
        logger.info(f"SERVER_PROTOCOL: Connection lost: {reason.getErrorMessage()}")

    def dataReceived(self, data):
        logger.info(f"SERVER_PROTOCOL: received data: {data}")


class ServerProtocolFactory(Factory):
    protocol = ServerProtocol

    def __init__(self, server):
        self.server = server

    def buildProtocol(self, addr):
        logger.info('SERVER_FACTORY: Connected.')
        return ServerProtocol(self.server)


class Server:
    def __init__(self,
                 port):

        self._port = port
        self._reactor = None

    def run(self):
        from twisted.internet import reactor

        # Start relay server
        factory = ServerProtocolFactory(self)

        # Use keys
        private_key = os.path.join('key.pem')
        self_signed = os.path.join('certificate.pem')

        # Authenticates the server to all potential clients for TLS communication
        try:
            context = ssl.DefaultOpenSSLContextFactory(private_key, self_signed)
        except OpenSSL.SSL.Error:
            raise AttributeError("The provided keys directory could not be found or does not contain the necessary keys.")
        logger.info(f"Listening on TLS to port {self._port}, with credentials {private_key} and {self_signed}")
        reactor.listenSSL(self._port, factory, context)

        self._reactor = reactor
        self._reactor.run()  # main Twisted reactor loop
        self._reactor = None  # remove when done


class ClientProtocol(Protocol):
    def __init__(self,
                 client):

        self._client = client

    def connectionMade(self):
        logger.info(f"CLIENT_PROTOCOL: connection made to server")

    def connectionLost(self, reason):
        logger.info(f"CLIENT_PROTOCOL: connection lost from server")

    def dataReceived(self, data):
        logger.info(f"CLIENT_PROTOCOL: received data ({data}).")


class TLSClientFactory(ReconnectingClientFactory):
    protocol = ClientProtocol

    def __init__(self, client):
        self._client = client
        self.maxDelay = self._client.recon_max_delay
        self.initialDelay = self._client.recon_initial_delay
        self.factor = self._client.recon_factor
        self.jitter = self._client.recon_jitter

    def startedConnecting(self, connector):
        logger.info('CLIENT_FACTORY: Started to connect.')

    def buildProtocol(self, addr):
        logger.info('CLIENT_FACTORY: Connected.')
        self.resetDelay()
        return ClientProtocol(client=self._client)

    def clientConnectionLost(self, connector, reason):
        logger.info(f'CLIENT_FACTORY: Lost connection.  Reason: {reason.getErrorMessage()}')
        ReconnectingClientFactory.clientConnectionLost(self, connector, reason)

    def clientConnectionFailed(self, connector, reason):
        logger.info(f'CLIENT_FACTORY: Connection failed. Reason: {reason.getErrorMessage()}')
        ReconnectingClientFactory.clientConnectionFailed(self, connector, reason)


class Client:
    def __init__(self,
                 ip_server,
                 port_server,
                 hostname='default',
                 recon_max_delay=60.0,
                 recon_initial_delay=10.0,
                 recon_factor=1.5,
                 recon_jitter=0.1):

        self._ip_server = ip_server
        self._port_server = port_server
        self._reactor = None
        self.to_server = None  # to communicate with the central relay
        self._hostname = hostname
        self.recon_max_delay = recon_max_delay
        self.recon_initial_delay = recon_initial_delay
        self.recon_factor = recon_factor
        self.recon_jitter = recon_jitter

    def run(self):
        from twisted.internet import reactor

        self_signed = os.path.join('certificate.pem')

        try:
            certData = FilePath(self_signed).getContent()
        except OpenSSL.SSL.Error:
            raise AttributeError("The provided keys directory could not be found or does not contain the necessary keys.")
        authority = ssl.Certificate.loadPEM(certData)
        reactor.connectSSL(
            host=self._ip_server,
            port=self._port_server,
            factory=TLSClientFactory(client=self),
            contextFactory=ssl.optionsForClientTLS(hostname=self._hostname, trustRoot=authority)
        )

        # Start the reactor
        self._reactor = reactor
        reactor.run()

        # When done, deallocate reactor memory
        self._reactor = None


if __name__ == "__main__":
    from multiprocessing import Process
    import time

    ser = Server(port=8123)
    p_ser = Process(target=ser.run, args=())
    p_ser.start()

    cli = Client(ip_server="127.0.0.1", port_server=8123)
    p_cli = Process(target=cli.run, args=())
    p_cli.start()

    while True:
        time.sleep(1)
```

Output:
```
INFO:root:Listening on TLS to port 8123, with credentials key.pem and certificate.pem
INFO:root:CLIENT_FACTORY: Started to connect.
INFO:root:CLIENT_FACTORY: Connected.
INFO:root:SERVER_FACTORY: Connected.
INFO:root:SERVER_PROTOCOL: Connection made from client
INFO:root:CLIENT_PROTOCOL: connection made to server
INFO:root:CLIENT_PROTOCOL: connection lost from server
INFO:root:CLIENT_FACTORY: Lost connection.  Reason: Connection was aborted locally using ITCPTransport.abortConnection.
INFO:root:SERVER_PROTOCOL: Connection lost: Connection to the other side was lost in a non-clean fashion: Connection lost.
INFO:root:CLIENT_FACTORY: Started to connect.
INFO:root:CLIENT_FACTORY: Connected.
INFO:root:SERVER_FACTORY: Connected.
INFO:root:SERVER_PROTOCOL: Connection made from client
INFO:root:CLIENT_PROTOCOL: connection made to server
INFO:root:CLIENT_PROTOCOL: connection lost from server
INFO:root:CLIENT_FACTORY: Lost connection.  Reason: Connection was aborted locally using ITCPTransport.abortConnection.
INFO:root:SERVER_PROTOCOL: Connection lost: Connection to the other side was lost in a non-clean fashion: Connection lost.
```

**Describe the correct behavior you'd like to see**
The correct behavior is the output obtained when installing `service-identity==21.1.0` instead of `23.1.0`:

```
INFO:root:Listening on TLS to port 8123, with credentials key.pem and certificate.pem
INFO:root:CLIENT_FACTORY: Started to connect.
INFO:root:CLIENT_FACTORY: Connected.
INFO:root:SERVER_FACTORY: Connected.
INFO:root:SERVER_PROTOCOL: Connection made from client
INFO:root:CLIENT_PROTOCOL: connection made to server
```

**Testing environment**
 - Operating System and Version: Microsoft Windows 11 Home 10.0.22621 N/A Build 22621
 - Twisted version: 23.10.0
 - Reactor: `twisted.internet.reactor`

**Comment by glyph** [comment]
Thanks for reporting this bug and for including an example. Much appreciated.

**Comment by glyph** [comment]
After some debugging, I believe this behavior is correct.  If you look at `service_identity`'s most recent changelog, you will see this: https://service-identity.readthedocs.io/en/stable/changelog.html#removed

> Support for commonName in certificates has been dropped. It has been deprecated since 2017 and isn’t supported by any major browser.

The certificate you have supplied here has a CommonName and no SubjectAltName, as I can see here in QuickLook on macOS:

![image](https://github.com/twisted/twisted/assets/716529/e37e70ca-f5a2-43f5-9bda-ae66be3f9cd7)

If you want to use `optionsForClientTLS`, you must generate certificates with SubjectAltName extensions that match the hostname you want to connect to, as any valid certificate authority would do.

If you want to generate certificates for testing, Twisted's own test suite contains an example of how to do this in a valid way with the `cryptography` module:

https://github.com/twisted/twisted/blob/88151eb454ebc30d3cd69e30ab6fd762cdbe3cfa/src/twisted/test/server.pem

**Comment by yannbouteiller** [comment]
Thanks a lot, that was the issue. Sorry for having missed that.

**Comment by glyph** [comment]
> Thanks a lot, that was the issue. Sorry for having missed that.

No worries, it took an embarrassing amount of time for me to figure out that that's what it was, despite the fact that I've bumped into this exact issue before :)

**Comment by adiroiban** [comment]
> No worries, it took an embarrassing amount of time for me to figure out that that's what it was, despite the fact that I've bumped into this exact issue before :)

It it tooks a lot of time to debug this, I would consider this a defect .

I see that https://github.com/pyca/service-identity/pull/52 is the PR for service_identity in which the commonName was removed

I see at https://github.com/pyca/service-identity/pull/52/files#diff-bf6d1c4ec44ff09a085657cc5b75da153a8cd025b8c72d4bd77d79e44cead072L144 that if there are no IDs, an empty list is returned, rather than raising an exception.

I would consider this something that can be improved

Maybe @hynek has some time to look into this and consider if this is working as expected, or we can improve the error handling.

I can try to help with a PR.

Regards

**Comment by glyph** [comment]
> It it tooks a lot of time to debug this, I would consider this a defect .

Good point.  Or, at least, room for an improved feature.

Although this particular error remains annoying to debug because it's something that *isn't* there.  Looking at the certificate, it appears at first glance to be "for" the hostname `default`, you have to know that the common name is not sufficient.

So while I would want service_identity to include the list of patterns from the certificate in the error, in this case, Twisted would need to, like, "lint" the certificate when loading it on the server side; doing these types of checks on every client connection is potentially expensive.  This particular certificate will not allow *any* verifying client to connect to it.  Unless of course you're loading it on purpose, because you have a client that invalidly validates CNs.

Or maybe we could have an explicit "debug mode" for the client that does do lots of extra checks on the server's certificate to help you diagnose issues.

**Comment by exarkun** [comment]
> Or maybe we could have an explicit "debug mode" for the client that does do lots of extra checks on the server's certificate to help you diagnose issues.

This might be good ... but also, it seems like there should be some lower-hanging fruit for improving on this failure.

The server may never be able to know exactly why a client decides to abandon the handshake, but the client should certainly know.  Instead of:

> INFO:root:CLIENT_FACTORY: Lost connection.  Reason: Connection was aborted locally using ITCPTransport.abortConnection.

it seems like the reason for `connectionLost` could instead be something like `SubjectAltNameMismatch(expected=xyz, observed=[...])`.  It would be even better if you could jam in the fact that the expected name was present in the commonName, but that's not good enough, but even just saying you looked for a certain subject alt name and didn't found it is an awful lot better than the current behavior.

It looks like this is something you might want to implement in service_identity itself since currently Twisted just relies on `service_identity.verify_hostname` to raise an exception and let's that be the reason ... however I also wonder if all of the code for juggling that exception in Twisted is working correctly, since it already seems like you should get a `service_identity.VerificationError` in this case, not the exception from the report which is more like ... `twisted.internet.error.ConnectionAborted`, I think?

**Comment by glyph** [comment]
> > INFO:root:CLIENT_FACTORY: Lost connection.  Reason: Connection was aborted locally using ITCPTransport.abortConnection.

`clientConnectionFailed` could definitely do better here; I'm not sure why that particular error is what comes through at this point.  I should note, however, that this is a bit of a weird quirk, because the correct error *does* come through on `ClientProtocol.connectionLost`, but this example doesn't print it.  When I add the reason to that log message (and switch to Twisted's logger), I get this:

```
2024-01-05T11:14:04-0800 [__mp_main__#info] CLIENT_PROTOCOL: connection lost from server [Failure instance: Traceback: <class 'service_identity.exceptions.VerificationError'>: VerificationError(errors=[DNSMismatch(mismatched_id=DNS_ID(hostname=b'default'))])
	/Users/glyph/Projects/Twisted/src/twisted/protocols/tls.py:247:_checkHandshakeStatus
	/Users/glyph/.virtualenvs/Twisted/lib/python3.11/site-packages/OpenSSL/SSL.py:2181:do_handshake
	/Users/glyph/.virtualenvs/Twisted/lib/python3.11/site-packages/OpenSSL/SSL.py:1444:wrapper
	/Users/glyph/Projects/Twisted/src/twisted/internet/_sslverify.py:1062:infoCallback
	--- <exception caught here> ---
	/Users/glyph/Projects/Twisted/src/twisted/internet/_sslverify.py:1172:_identityVerifyingInfoCallback
	/Users/glyph/.virtualenvs/Twisted/lib/python3.11/site-packages/service_identity/pyopenssl.py:54:verify_hostname
	/Users/glyph/.virtualenvs/Twisted/lib/python3.11/site-packages/service_identity/hazmat.py:74:verify_service_identity
	]
```

**Comment by adiroiban** [comment]
Thanks Glyph for the info.

As we get the `service_identity.exceptions.VerificationError` in Twisted code, I think that we are ok.

I have created a ticket for `service_identity` https://github.com/pyca/service-identity/issues/66

**Comment by hynek** [comment]
https://github.com/pyca/service-identity/releases/tag/24.1.0

**Comment by adiroiban** [comment]
Many thanks Hynek
