### ISSUE TITLE
Is it possible to monitor reactor task execution? Or event detection?

### ISSUE THREAD

**Issue by MacDaddy1660B** [twisted/twisted#12091]
I'm developing a twisted application and it's having problems running on MacOS platforms, but works fine on Windows or Linux. The application's reactor seems to be getting stuck on a task, and CPU usage shoots up. The application doesn't raise any exceptions or anything. Is there any way to enable debugging, or something similar, to see what the reactor is executing and find out where my application is getting stuck?

I think what I want to know is when the reactor executes a new task, or detects a new event.

My reactor has tk support installed, as it is part of a GUI application. It is a select reactor.

Things seem work just fine with Python 3.8, but nothing newer than that.

I've searched around for issues related to this (and have asked some minor questions about it in #12051 ). So far I haven't found anything helpful, and some useful logging messages might be helpful for me.

Thanks.

**Comment by glyph** [comment]
Thanks for using Twisted; sorry it's not working great for you right now.

In a word: no.

In more words: this isn't really an "issue" in Twisted, since there may or may not be anything for us to do here, so I'm going to close it to avoid cluttering up the issue tracker.  You might have better luck with a mailing list post if you want help debugging your application (https://mail.python.org/mailman3/lists/twisted.python.org/) or if you wanted to request a more specific "debug" feature here, you should open a feature request describing what you want in more detail.

In the meanwhile, the `spindump` tool on macOS might provide at least a little insight into when your application is stuck.  Get it into a state where the CPU is busy, then run it and have a look at the text file it spits out.

**Comment by MacDaddy1660B** [comment]
Thank you. I thought I had selected a feature request for this post. I'll do as you say. I appreciate the help.

**Comment by glyph** [comment]
> Thank you. I thought I had selected a feature request for this post. I'll do as you say. I appreciate the help.

I am guessing you did (none of the bug labels were applied), but you didn't fill out the questions in the relevant template, and the request is just a bit too general and vague to be worth tracking as a feature just yet; using issues for general discussions makes triage harder since it adds a bunch of ambiguity to the process.
