### ISSUE TITLE
Stop calling Failure.cleanFailure() in Deferred error handling

### ISSUE THREAD

**Issue by itamarst** [twisted/twisted#12234]
This is a performance enhancement, but potentially also a UX improvement.

The motivation for `cleanFailure()` being called by `Deferred` is to prevent memory leaks. However, it was added in 2002, before Python had reasonable garbage collection, when circular references were therefore much more of a problem. These days circular references will get cleaned up just fine.

Lack of `cleanFailure` will therefore increase memory usages in a much more limited set of circumstances: when a `Deferred` with an error continues to be held on to without any error handling being done. This is certainly possible, but it's far less common of a situation.

If `cleanFailure` is dropped, that means the `Failure` in a `Deferred` will always have a traceback, which means `Failure.frames` becomes unnecessary in most situations. Which means Python's normal (and these days, superior, e.g. column locations not just line locations) display can be used in most situations.

The benefits would therefore be:

* Somewhat faster `Failure` handling in `Deferred`.
* Improved tracebacks from `Failure` in most situations, taking advantage of the work Python has done to show more granular sources of an exception than just lines.

The downsides:

* Increased memory usage from `Deferred` with error that isn't handled.

**Comment by glyph** [comment]
There are a few additional downsides:

1. *Some* objects (as far as I can tell, only "C extension objects that haven't migrated from `tp_del` to `tp_finalize`") can still create [uncollectible cycles](https://docs.python.org/3.12/library/gc.html#gc.garbage), and exception stack traces can contain references to anything
2. this is going to put a bunch of additional load on the garbage collector, which could mean longer GC pauses, because almost every exception is going to contain a cycle, and thanks to the fact that Failure lives a little longer than Exceptions generally, we may see it . Or… not? we are already burning up a bunch of time doing this manual cleaning, which honestly will probably dwarf any work for the GC
3. ~~this may create silent leaks in places where a failed `Deferred` is stashed away on object, and `cleanFailure` had previously cleared out stack-based reference to something large, and it no longer does.~~ oops that was a restatement of your downside

**Comment by glyph** [comment]
(I think I am generally in favor of this I think but I'm just nervous about all the unpredictable interactions this might provoke.)

**Comment by itamarst** [comment]
https://docs.python.org/3/library/traceback.html#traceback.clear_frames is one option for making `cleanFailure` potentially much cheaper, and it would remove the circular references.

**Comment by itamarst** [comment]
Ah, but `clear_frames()` would only impact the where-the-exception-was-raised part (`Failure.frames`), not the where-the-Failure-was-created part (`Failure.stack`) which the worse part since the latter is more likely to include the Deferred. So might not be a full solution.

**Comment by itamarst** [comment]
We can do that manually though, and it won't clear everything (can't clear frames that are still in use) but it'll get most things.

**Comment by itamarst** [comment]
Further thought suggests that it'll be impossible to prevent circular references with `frame.clear()`, since the parent frame will both have a reference to the Deferred and it will still be running, and therefore cannot be cleared.

**Comment by itamarst** [comment]
One idea would be:

1. Instead of calling `cleanFailure`, `Deferred` registers the `Failure` with a global `WeakSet`.
2. Every few seconds, the reactor goes through that set, removes all entries and calls `cleanFailure()` on them.

This means anything that gets cleaned up quickly will be cheaper to create, and everything that doesn't get cleaned up quickly has circular references wiped in not too long.

**Comment by itamarst** [comment]
Looking at how `asyncio` does this with `Future`, it just... keeps the traceback around and doesn't worry about circular references: https://github.com/python/cpython/blob/main/Lib/asyncio/futures.py (`_exception_tb` on `Future`).

**Comment by itamarst** [comment]
Given #12230 will be merged, this is somewhat less pressing performance-wise, but it would still be a nice boost. But a nice boost to error handling so maybe less critical.
