### ISSUE TITLE
Remove the deprecated module `twisted.python.constants`

### ISSUE THREAD

**Issue by gudnimg** [twisted/twisted#12361]
**Is your feature request related to a problem? Please describe.**
Idea for cleanup

**Describe the solution you'd like**
`twisted.python.constants` has been deprecated since Twisted 16.5.0 and just redirects to constantly package. I would like to propose removing this module as cleanup.

**Comment by gudnimg** [comment]
I'm not sure how long the deprecation should last, but isn't 8 years enough? :)

There is also `twisted.python.url`, I can remove that too if no one is against it.

**Comment by adiroiban** [comment]
Hi and thanks for looking into the cleanup

8 years is enough and I am happy to approve a PR that removed twisted.python.constants

For twisted.python.url, is best to remove it in a separate PR.

---

The compatibility is defined here

https://docs.twisted.org/en/latest/development/compatibility-policy.html#the-first-one-s-always-free

and there is also this note

> Removal should not be undertaken just to follow a timeline. Twisted should strive, as much as practical, not to break applications relying on it.

-------

so, as long as the deprecated code does not inflict a performance penalty and does not require extra maintanance effort, we generaly don't remove the deprecated code

if the deprecated code has security issues and the fix is only available in the replacement code, then there is a higher urgenty to remove the deprecated code

but, if the depecated code works as expected, the deprecation warning is just to let you know that the code is no longer "active" and if you want the latests and greates features, you should look at using the replacement code

but if the deprecated code works for you and don't need extra work from Twisted team... that's fine for us
