### ISSUE TITLE
twisted.internet.endpoints._parse() should be public

### ISSUE THREAD

**Issue by p12tic** [twisted/twisted#12385]
Twisted does not offer any tools to interact with endpoint description strings. Exposing this would be useful in middleware code that would behave differently depending on what exact description string is.

Example of third-party functionality that currently uses this private API: https://github.com/buildbot/buildbot/pull/8253

**Comment by glyph** [comment]
I am not clear on why this functionality is desirable. Third party code should *not* be parsing endpoint descriptions like this, as parsing and reacting to twisted's strings destroys the actual utility of the string-endpoint system. For example, how would this handle an HAProxy connection string? A launchd or systemd endpoint? rather than parsing, we should want an interrogator interface that asks "where is this publicly exposed" (which would need to be asynchronous) if we want to support the ability of clients to translate to things like HTTP (or websocket) URLs.

**Comment by p12tic** [comment]
Thanks for comment.

I would say that there's still a lot of utility in using endpoint description strings even if only few protocols are supported. Consider the breadth of parameters that the tls client endpoint supports. In the case of Buildbot the best solution is to pass the user supplied string as is and point to Twisted documentation about what kind of connection strings Buildbot supports.

I agree that some of utility is destroyed if using the Buildbot approach of having special cases for each protocol. However, I think this is unavoidable: consider e.g. unix protocol. There's no meaning in host and port because this is local connection. So there will need to be special case for unix anyway and accordingly there's no additional loss of generality.

Ultimately what this issue and PR is about is simply exposing part of functionality that is already in Twisted. The objective is not to prescribe how endpoints strings should be used, but simply to avoid duplicate effort downstream. The user does not always have time for perfect solution, so if Twisted does not expose `_parse`, this will simply cause inferior workarounds to be developed.

I think with regards to Twisted the most important consideration for this issue and PR is whether the format of endpoint strings is universal and stable. Right now the code is such that all endpoint strings must be supported by `_parse`. If this will stay for the foreseeable future, then there's no downside to expose `_parse` effectively committing to this format for any future protocols. If not, then this issue and PR does not make sense on these grounds.

**Comment by glyph** [comment]
> I think with regards to Twisted the most important consideration for this issue and PR is whether the format of endpoint strings is universal and stable

I really don't want to commit to this. We do need to provide some stability for deployments: if `tcp:80` means something now, it must continue to mean that thing, but we should be able to reserve the right to add parameters at any time, because new platform-level esoterica are constantly emerging.

Buildbot needs to support a limited number of protocols anyway, why not go in the other direction and specify the `ws://` URL in the UI for buildbot, parse that, and then construct one of the limited number of endpoints with an endpoint class? If you know what endpoints you want, the Python API is an existing, stable interface to get them.

**Comment by p12tic** [comment]
> I really don't want to commit to this. We do need to provide some stability for deployments: if tcp:80 means something now, it must continue to mean that thing, but we should be able to reserve the right to add parameters at any time, because new platform-level esoterica are constantly emerging.

Sorry, this is not what I meant. I meant only much weaker stability that the endpoint strings are composed of parameters separated by `:` with `=` used to mean named parameters.

**Comment by p12tic** [comment]
> Buildbot needs to support a limited number of protocols anyway, why not go in the other direction and specify the ws:// URL in the UI for buildbot, parse that, and then construct one of the limited number of endpoints with an endpoint class? If you know what endpoints you want, the Python API is an existing, stable interface to get them.

Sounds good.

**Comment by glyph** [comment]
Cool. I hope that with that interface there's some hope for a future world where things like proxy/SSH/etc endpoints could be integrated on the backend, rather than breaking inscrutably if you try to use them on the frontend :)
