### ISSUE TITLE
Add maybeAwaitable() to help transparent migration of inlineCallbacks code to coroutines

### ISSUE THREAD

**Issue by p12tic** [twisted/twisted#12399]
Currently it's impossible to transparently migrate inlineCallbacks code to coroutines because `await` works differently than `yield`. `yield` supports plain values and passes them through itself unmodified, but await accepts only awaitable.

Using `maybeDeferred` is an option, but it's not perfect, because it creates a new Deferred object unconditionally. Ideally, Twisted would have something like this:

```
async def maybeAwaitable(d):
    if iscoroutine(coro) or inspect.isgenerator(coro) or isinstance(d, Deferred):
        return await d
    return d
```

this would allow to replace `x = yield y` with `x = await maybeAwaitable(y)` in all functions without too much thinking.

What do you think?

**Comment by glyph** [comment]
Personally when I am converting some code like this I add some basic type annotations and mypy will tell me if I have a coroutine or not; in general you *should* know whether you're calling an async thing, and I feel like our original design for `yield` wasted a lot of time in `isinstance`, driven by the original decision of `Deferred`'s callback instance check.  In the callback-chain approach, you kinda need it to allow for one callback to defer the next one, because a callback is like the front *and* the back half of an `await`.

There's an extra dimension to the complexity here where a "fire and forget" method like that probably needs to take Future and Task into account as well; and then maybe you want the things Curio or Trio await, too.  I think this immediate scope creep is a good indication that this is not a great direction to go.

That said, if this is an important porting tool for you and my approach *doesn't* work, I don't think we should necessarily reject this out of hand.

**Comment by graingert** [comment]
`inspect.isgenerator(coro)` will not necessarily work with `await`, and you don't need to check for Deferred because it's already awaitable!

you can make your own as_coro function:

```python
@typing.overload
async def as_coro[T](maybe_awaitable: Awaitable[T]) -> T:
    ...

@typing.overload
async def as_coro[T](maybe_awaitable: T) -> T:
    ...

async def as_coro[T](maybe_awaitable: Awaitable[T] | T, /) -> T:
    return (
        (await maybe_awaitable)
        if inspect.isawaitable(maybe_awaitable)
        else maybe_awaitable
    )
```

but the typing is a bit broken, because if you actually don't know at type check time if something is Awaitable or not the overloads don't work

if you really need this I'd recommend using a ternary every time you need it:

```python
maybe_awaitable = maybe_async()
v = (await maybe_awaitable) if inspect.isawaitable(maybe_awaitable) else maybe_awaitable
```


because this is not twisted defer.Deferred, and it's a simple one-liner, I'd recommend we don't include this util in twisted and just get everyone to write their own

**Comment by p12tic** [comment]
> Personally when I am converting some code like this I add some basic type annotations and mypy will tell me if I have a coroutine or not; in general you should know whether you're calling an async thing

In general I agree, the problem occurs when there's third-party user code involved which cannot be changed due to backwards compatibility guarantees.

**Comment by glyph** [comment]
I feel a little bad that you're getting so much pushback on these ideas! I really appreciate the energy though and I hope this is not too discouraging :)
