### ISSUE TITLE
Automate updating the howtos on the twistedmatrix web site

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#2890]
|[<img alt="radix's avatar" src="https://avatars.githubusercontent.com/u/227068?s=50" width="50" height="50">](https://github.com/radix)| @radix reported|
|-|-|
|Trac ID|trac#2890|
|Type|enhancement|
|Created|2007-11-12 20:04:46Z|

This currently involves unix commands (see ReleaseProcess#Updatedocumentation).

<details><summary>Searchable metadata</summary>

```
trac-id__2890 2890
type__enhancement enhancement
reporter__radix radix
priority__normal normal
milestone__totally_automated_release_infrastructure totally automated release infrastructure
branch__ 
branch_author__ 
status__new new
resolution__None None
component__release_management release management
keywords__ 
time__1194897886000000 1194897886000000
changetime__1448145359334379 1448145359334379
version__None None
owner__ 
cc__thijs cc__michael@...
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="thijstriemstra's avatar" src="https://avatars.githubusercontent.com/u/305679?s=50" width="50" height="50">](https://github.com/thijstriemstra)<a name="note_3"></a>|@thijstriemstra commented|
|-|-|

Is this something others can work on, or is it basically limited to people that have access to the twistedmatrix webserver?

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|

**Comment by adiroiban** [comment]
I think that this can be closed. It was not actioned for a long time.

The current website is hosted via GitHub Pages and hosted here 
https://github.com/twisted/twisted.github.io

I guess that you can find a way to auto-magically push a commit to that repo and will auto-update the page.

But looks like a lot of work...
and I guess that if someone will want to work on it will open a new ticket rather than star working on this one.

Feel free to reopen.
